server:
  port: 8082

spring:
  config:
    import: optional:classpath:application-secret.yml
  application:
    name: product
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product
    username: product_user
    password: 1234
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    listener:
      missing-topics-fatal: true
      ack-mode: record
      concurrency: 3

alert:
  discord:
    action-webhook-url: ${ALERT_DISCORD_ACTION_WEBHOOK_URL:}
    incident-webhook-url: ${ALERT_DISCORD_INCIDENT_WEBHOOK_URL:}
    defect-webhook-url: ${ALERT_DISCORD_DEFECT_WEBHOOK_URL:}
