server:
  port: 8082

spring:
  application:
    name: product
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/product
    username: product_user
    password: 1234
