server:
  port: 8080

spring:
  application:
    name: order
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/order
    username: order_user
    password: 1234

service:
  product: http://127.0.0.1:8082
  point: http://127.0.0.1:8081
  payment: http://127.0.0.1:8083
