server:
  port: 8083

spring:
  application:
    name: payment
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/payment
    username: payment_user
    password: 1234
