server:
  port: 8081

spring:
  application:
    name: point
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/point
    username: point_user
    password: 1234
