CREATE DATABASE IF NOT EXISTS `order`   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `product` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `point`   CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `payment` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'order_user'@'%'   IDENTIFIED BY '1234';
CREATE USER IF NOT EXISTS 'product_user'@'%' IDENTIFIED BY '1234';
CREATE USER IF NOT EXISTS 'point_user'@'%'   IDENTIFIED BY '1234';
CREATE USER IF NOT EXISTS 'payment_user'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON `order`.*   TO 'order_user'@'%';
GRANT ALL PRIVILEGES ON `product`.* TO 'product_user'@'%';
GRANT ALL PRIVILEGES ON `point`.*   TO 'point_user'@'%';
GRANT ALL PRIVILEGES ON `payment`.* TO 'payment_user'@'%';

FLUSH PRIVILEGES;
